backend:
  name: github
  repo: Anasong1/Kdell-infotech-site
  branch: main
  base_url: https://kdell-cms-oauth.ngoasongang.workers.dev
  auth_endpoint: auth

site_url: https://kdellinfotech.com
display_url: https://kdellinfotech.com
